sudo: false

language: node_js

node_js:
  - "10"
  - "8"
  - "6"
  - "4"

# Required for NodeJS v4 and higher
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
    - node_modules

after_success:
  - npm run coveralls
  
